### ISSUE TITLE
Add the notification drawer 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-react-demo-app#25]
Add the notification drawer to the demo app

**Comment by amarie401** [comment]
cc @priley86

**Comment by amarie401** [comment]
I think we are at a good point with the additions we have made so far with the vertical nav, masthead, list view, table and filter components.

Going to close this issue for now since there are no current plans to add this to the demo app after discussing with @priley86 and @dgutride . FYI @LHinson 

If we decide to add this component to the demo app in the future then we can re-open this issue.
